spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect <- 이런식으로 DB를 쉽게 변경가능
#        show_sql: true # sql문을 콘솔에 남긴다.
        format_sql: true # format에 맞춰 예쁘게 나오게 해줌

logging.level:
  org.hibernate.SQL: debug  # sql문을 콘솔에 남기는게 아니라 log 파일로 남긴다.
#  org.hibernate.type: trace # 바인딩 된 파라미터까지 볼 수 있다.(지저분할 수 있음)